services:
  web:
    image: ghcr.io/andreab-1/inventree-companion-app:latest
    restart: unless-stopped
    environment:
      INVENTREE_URL: ${INVENTREE_URL}
      INVENTREE_TOKEN: ${INVENTREE_TOKEN}
    ports:
      - "8000:8000"
